---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections: 
- path: content/work
  label: Arbeit
  templates:
  - arbeit
- path: content
  label: Seite
  templates:
  - seite
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: 0.42.1
